# alice send message
POST {{host}}/channels/test/messages
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "user": "alice",
  "message": "hey bob!"
}

###
# bob send message
POST {{host}}/channels/test/messages
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "user": "bob",
  "message": "hey alice!"
}
